# Generated by Django 3.1 on 2020-09-28 15:37

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prezzo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('categoria', models.CharField(choices=[('N', 'Nike'), ('A', 'Adidas'), ('J', ' Air Jordan'), ('L', 'Luxury Brands'), ('O', 'Altri Brands')], max_length=2)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(upload_to='')),
                ('tagliaEU', models.FloatField(validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(47.0)])),
                ('condizioni', models.CharField(choices=[('N', 'Deadstock(New)'), ('U', 'Used')], max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('release', models.DateTimeField(auto_now_add=True)),
                ('autore_vendita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scarpe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
