# Generated by Django 3.1 on 2020-09-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200928_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='release',
        ),
    ]
