# Generated by Django 3.1 on 2020-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
