# Generated by Django 3.1 on 2020-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201009_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
