# Generated by Django 3.1 on 2020-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_item_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_ordered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
