# Generated by Django 3.1 on 2020-10-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_shoppingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shoppingaddress'),
        ),
    ]
