# Generated by Django 3.1 on 2020-10-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_order_shopping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(blank=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compratore', to=settings.AUTH_USER_MODEL)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
