# Generated by Django 3.1 on 2020-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201019_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
