# Generated by Django 3.1 on 2020-10-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_itemconsigliati'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='consigliato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='categoriaA',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='categoriaJ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='categoriaL',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='categoriaN',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='categoriaO',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='condizioneN',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='condizioneU',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemconsigliati',
            name='media_taglia',
            field=models.FloatField(default=35.0, validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(47.0)]),
        ),
    ]
