# Generated by Django 3.1 on 2020-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201023_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconsigliato',
            name='num_item',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemconsigliato',
            name='sum_taglia',
            field=models.FloatField(default=0),
        ),
    ]
