# Generated by Django 3.1 on 2020-10-23 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201023_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='categoriaA',
        ),
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='categoriaJ',
        ),
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='categoriaL',
        ),
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='categoriaN',
        ),
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='categoriaO',
        ),
        migrations.AddField(
            model_name='itemconsigliato',
            name='prezzo',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
