# Generated by Django 3.1 on 2020-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201023_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconsigliato',
            name='sum_prezzo',
            field=models.FloatField(default=0),
        ),
    ]
