# Generated by Django 3.1 on 2020-10-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201023_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='items',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
