# Generated by Django 3.1 on 2020-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201023_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='items',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='items',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
