# Generated by Django 3.1 on 2020-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201023_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
    ]
