# Generated by Django 3.1 on 2020-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201023_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='items',
            field=models.ManyToManyField(null=True, to='core.OrderItem'),
        ),
    ]
