# Generated by Django 3.1 on 2020-10-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201023_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
