# Generated by Django 3.1 on 2020-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='media_taglia',
        ),
        migrations.RemoveField(
            model_name='itemconsigliato',
            name='sum_taglia',
        ),
    ]
