# Generated by Django 3.1 on 2020-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20201026_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='compratore',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
