# Generated by Django 3.1 on 2020-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ManyToManyField(to='accounts.Address'),
        ),
    ]
