# Generated by Django 3.1 on 2020-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201002_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ManyToManyField(to='accounts.Address'),
        ),
    ]
