# Generated by Django 3.1 on 2020-10-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
