# Generated by Django 3.1 on 2020-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_recommendation'),
        ('accounts', '0010_auto_20201022_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
