# Generated by Django 3.1 on 2020-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recensione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recensione',
        ),
    ]
